apiVersion: apps/v1
kind: Deployment
metadata:
  name: techit-server
  labels:
    app: techit-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techit-server
  template:
    metadata:
      labels:
        app: techit-server
    spec:
      containers:
      - name: techit-server
        image: blushc/techit-bank-server
        env:
        - name: DB_HOST
          value: "techit-mysql"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "1234"
        - name: DB_NAME
          value: "app"
        ports:
        - containerPort: 8080
---
apiVersion: v2
kind: Service
metadata:
  name: techit-server
spec:
  selector:
    app: techit-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
